### ISSUE TITLE
Error with starwars data set in dplyr

### ISSUE THREAD

**Issue by durraniu** [gsimchoni/kandinsky#1]
> library(kandinsky)
> kandinsky(starwars)
> Error in sort.list(y) : 'x' must be atomic for 'sort.list' Have you called 'sort' on a list?

I think its because the data set also contains character variables. So, I only selected 2 numeric variables:  

> kandinsky(starwars[,c("height", "mass")])
> Error in calcCurveGrob(x, x$debug) : end points must not be identical  

But this time few shapes did appear.

**Comment by gsimchoni** [comment]
You actually hit 2 issues there. `kandinsky` is OK with `character` columns, e.g. starwars$name:

`kandinsky(starwars[, 1:10])`

works fine.

The first issue is failing to handle `list` columns.

The second issue is weird. Because: `kandinsky(starwars[, "height"])` and `kandinsky(starwars[, "mass"])` seem to work fine, just not `kandinsky(starwars[,c("height", "mass")])`.

Will look into both, thank you.

**Comment by gsimchoni** [comment]
OK, found the reason for the second issue. It occurred because the same value was entered into `grid.curve`, in this case 0.5 because at the final few rows of `starwars[, c("height", "mass"])` all values are `NA`. But again, this could happen also for `grid.curve(0.1, 0.1, 0.1, 0.1)`. Great catch.

**Comment by gsimchoni** [comment]
Fixed, try now:

![image](https://user-images.githubusercontent.com/9554580/28686566-4024e50e-7314-11e7-97ba-cfc6de1eb176.png)

**Comment by durraniu** [comment]
Thanks. It looks beautiful!
